### PR TITLE
(GH-824)(GH-812) Improve code folding speed

### LINKED ISSUE #812: Code Folding may not work with DSC keywords
Code folding is not currently tested against DSC scripts e.g.

https://github.com/PowerShell/ActiveDirectoryCSDsc/blob/79431371bd17a3a872bc71b8463b5bca29a95071/Examples/Resources/AdcsCertificationAuthority/1-InstallCertificationAthority.ps1

`Configuration`

`Node`

`AdcsCertificationAuthority `

### LINKED ISSUE #824: Code folder uses sub-optimal conventions and processes
The syntax aware code folder was initially adapted from the Typescript version.  However when porting to C# the behaviour was correct but the implementation was slow and created many objects.

This ticket tracks the effort to speed up the code folding provider.

### PR DESCRIPTION
**Pull request by glennsarti**
Previously there were no tests for PowerShell classes.  This commit adds a simple
test for this scenario to ensure future changes do not break folding.

Previously the folding provider created many intermediate arrays and lists and
required post-processing.  This commit changes the behaviour to use an
accumlator patter with an extended Dictionary class.  This new class adds a
`SafeAdd` method to add FoldingRanges, which then has the logic to determine if
the range should indeed be added, for example, passing nulls or pre-existing
larger ranges.

By passing around this list using ByReference we can avoid creating many objects
which are just then thrown away.

Previously each token type detection was separated into discrete blocks
to make reading the code easier. However this meant there were many
enumerations of the Tokens array as well as passing around intermediate
arrays/lists.  This commit takes the individual methods and overlaps them
to reduce the number of enumerations and regular expression matching to
a minimum.

Previously the code folding was not tested against DSC configuration scripts.
This commit adds tests for a sample DSC script to ensure the folding occurs at the correct
places

Fixes #824
Fixes #812

### CODE REVIEW

**Comment by glennsarti** [comment]
@TylerLeonhardt @rjmholt These are the code folding improvements from the AST work I did, but now are Token processing only.

Managed to shave nearly 50% runtime and probably reduced objects allocated significantly.

Raw data;
Given a script with 4096 foldable regions;

Before
```
Duration: 230.5017  <--- Ignored
Duration: 32.9991
Duration: 40.5561
Duration: 35.4358
Duration: 38.018
Duration: 36.9978
Duration: 34.0487
Duration: 31.9936
Duration: 34.9428
Duration: 41.0429
Duration: 36.0661
Duration: 34.0165
Duration: 37.0365
Duration: 34.026
Duration: 33.9919
Duration: 36.0026
Duration: 34.585
Duration: 39.5611
Duration: 34.5185
Duration: 34.5172
Avg Duration: 35.8082210526316
```

After
```
Duration: 132.0037  <--- Ignored
Duration: 15.9972
Duration: 15.963
Duration: 22.0686
Duration: 15.9767
Duration: 14.9559
Duration: 30.5756
Duration: 18.0449
Duration: 18.9995
Duration: 32.9537
Duration: 16.0499
Duration: 17.0227
Duration: 20.4783
Duration: 16.9985
Duration: 14.0394
Duration: 21.9654
Duration: 17.5853
Duration: 14.5099
Duration: 15.039
Duration: 26.9451
Avg Duration: 19.2720315789474
```

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 1]
```diff
@@ -21,103 +21,120 @@ internal static class TokenOperations
...
+                // Find unopinionated variable names ${ \n \n }
+                // Find contiguous expandable here strings @" -> "@
+                if ((
+                    (token.Kind == TokenKind.HereStringLiteral) ||
+                    (token.Kind == TokenKind.Variable) ||
+                    (token.Kind == TokenKind.HereStringExpandable)
+                    ) && (token.Extent.StartLineNumber != token.Extent.EndLineNumber)) {
+                    refList.SafeAdd(CreateFoldingReference(token, token, RegionKindNone));
+                }
+            }
```
Comment (TylerLeonhardt) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: I think a switch might be slightly more readable here:

```csharp
            switch (token.Kind)
            {
                case LCurly:
                case AtCurly:
                    tokenCurlyStack.Push(token);
                    break;

                case RCurly:
                    if (tokenCurlyStack.Count > 0)
                    {
                        refList.SafeAdd(CreateFoldingReference(tokenCurlyStack.Pop(), token, RegionKindNone));
                    }
                    break;

                case LParen:
                case AtParen:
                case DollarParen:
                    tokenParenStack.Push(token);
                    break;

                case RParen:
                    if (tokenParenStack.Count > 0)
                    {
                        refList.SafeAdd(CreateFoldingReference(tokenParenStack.Pop(), token, RegionKindNone));
                    }
                    break;

                case HereStringLiteral:
                case Variable:
                case HereStringExpandable:
                    if (token.Extent.StartLineNumber != token.Extent.EndLineNumber)
                    {
                        refList.SafeAdd(CreateFoldingReference(token, token, RegionKindNone));
                    }
                    break;

                default:
                    break;
            }
```

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 2]
```diff
@@ -21,103 +21,120 @@ internal static class TokenOperations
...
 
             // Find matching comment regions   #region -> #endregion
-            foldableRegions.AddRange(
-                MatchCustomCommentRegionTokenElements(tokens, RegionKindRegion)
-            );
-
+            // Given a list of tokens, find the tokens that are comments and
+            // the comment text is either `# region` or `# endregion`, and then use a stack to determine
```
Comment (TylerLeonhardt) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: is it `# region` or `#region`? I think the latter, right?

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 1 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Forgot about those.  Changed.

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 2 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Regex is `"^\s*#region\b"` so yes latter.  Fixed.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 3]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                    continue;
+                }
 
-            // Some editors have different folding UI, sometimes the lastline should be displayed
-            // If we do want to show the last line, just change the region to be one line less
-            if (ShowLastLine) {
-                foldableRegions.ForEach( item => { item.EndLine--; });
+                if (!IsBlockComment(index, tokens)) { continue; }
+                // Regex's are very expensive.  Use them sparingly!
+                // Processing for # region -> # endregion
```
Comment (TylerLeonhardt) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]:
```suggestion
                // Processing for #region -> #endregion
```

**Comment by TylerLeonhardt** [comment]
I'm good. Let's wait on 1 more 👍

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs [hunk 4]
```diff
@@ -1382,13 +1382,15 @@ private bool IsQueryMatch(string query, string symbolName)
             // TODO Should be using dynamic registrations
             if (!this.currentSettings.CodeFolding.Enable) { return null; }
             var result = new List<FoldingRange>();
+            ScriptFile script = editorSession.Workspace.GetFile(documentUri);
+            // If we're showing the last line, decrement the Endline of all regions by one.
+            int endLineOffset = this.currentSettings.CodeFolding.ShowLastLine ? -1 : 0;
             foreach (FoldingReference fold in TokenOperations.FoldableRegions(
-                editorSession.Workspace.GetFile(documentUri).ScriptTokens,
-                this.currentSettings.CodeFolding.ShowLastLine))
+                script.ScriptTokens).ToArray())
```
Comment (rkeithhill) [inline src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: Could you assign `TokenOperations.FoldableRegions(script.ScriptTokens).ToArray()` to an intermediate variable (`foldableRegions`?) for better debuggability and so this foreach doesn't have to wrap to a second line?

File: src/PowerShellEditorServices/Language/FoldingReference.cs [hunk 5]
```diff
@@ -60,4 +61,33 @@ public class FoldingReference: IComparable<FoldingReference>
...
+    public class FoldingReferenceList : Dictionary<int, FoldingReference>
+    {
+        /// <summary>
+        /// Adds a FoldingReference to the list and enforces ordering rules e.g. Only one fold per start line
+        /// </summary>
+        public void SafeAdd(FoldingReference item)
+        {
+            if (item == null) { return; }
+            FoldingReference currentItem;
+            TryGetValue(item.StartLine, out currentItem);
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/FoldingReference.cs]: Doesn't the version of C# we use support `TryGetValue(item.StartLine, out FoldingReference currentItem)`?  Also, it is a bit unusual to see a `Try*` method, which returns a bool, not used inside an `if` condition e.g. `if (TryGetValue(...)) { ... }`.  It appears you are relying on the TryGetValue to set the current item to null but you could just as well use the return value from `TryGetValue` to determine if `currentItem` will be valid or not.  IMO the intent would be more clear in the code.

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs (hunk 4 above)
Comment (rkeithhill) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: BTW is it really necessary to create/copy a new array here - which I see the ToArray method below is doing?  The Dictionary.Values property will return an `IEnumerable<FoldingReference>` which is all you need to iterate (foreach) over it.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 6]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                    refList.SafeAdd(CreateFoldingReference(token, token, RegionKindComment));
+                    continue;
+                }
 
-            // Some editors have different folding UI, sometimes the lastline should be displayed
-            // If we do want to show the last line, just change the region to be one line less
-            if (ShowLastLine) {
-                foldableRegions.ForEach( item => { item.EndLine--; });
+                if (!IsBlockComment(index, tokens)) { continue; }
+                // Regex's are very expensive.  Use them sparingly!
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline before comment section of code

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 7]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                // Processing for #region -> #endregion
+                if (s_startRegionTextRegex.IsMatch(token.Text))
+                {
+                    tokenCommentRegionStack.Push(token);
+                    continue;
+                }
+                if (s_endRegionTextRegex.IsMatch(token.Text))
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline before different `if` statement.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 8]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                {
+                    // Mismatched regions in the script can cause bad stacks.
+                    if (tokenCommentRegionStack.Count > 0)
+                    {
+                        refList.SafeAdd(CreateFoldingReference(tokenCommentRegionStack.Pop(), token, RegionKindRegion));
+                    }
+                    continue;
+                }
+                // If it's neither a start or end region then it could be block line comment
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 9]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                // Processing for blocks of line comments # comment1\n# comment2\n...
+                int thisLine = token.Extent.StartLineNumber - 1;
+                if ((blockStartToken != null) && (thisLine != blockNextLine))
+                {
+                    refList.SafeAdd(CreateFoldingReference(blockStartToken, blockNextLine - 1, RegionKindComment));
+                    blockStartToken = token;
+                }
+                if (blockStartToken == null) { blockStartToken = token; }
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 10]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
+                blockNextLine = thisLine + 1;
+            }
+            // If we exit the token array and we're still processing comment lines, then the
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 11]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
-                // list is sorted at this point, so we can use BinarySearch.
-                int index = foldableRegions.BinarySearch(item);
-                if (index == 0) { return false; }
-                return (item.StartLine == foldableRegions[index - 1].StartLine);
-            });
+            for (int index = 0; index < tokens.Length; index++)
+            {
+                Token token = tokens[index];
+                if (token.Kind != TokenKind.Comment) { continue; }
+                // Processing for comment regions <# -> #>
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Insert newline here. It really helps when other people read your code.

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 12]
```diff
@@ -21,103 +21,140 @@ internal static class TokenOperations
...
-            TokenKind.LParen,
-            TokenKind.AtParen,
-            TokenKind.DollarParen
-        };
+        // These regular expressions are used to match lines which mark the start and end of region comment in a PowerShell
+        // script. They are based on the defaults in the VS Code Language Configuration at;
+        // https://github.com/Microsoft/vscode/blob/64186b0a26/extensions/powershell/language-configuration.json#L26-L31
+        static private readonly Regex s_startRegionTextRegex = new Regex(
+           @"^\s*#region\b",
+            RegexOptions.IgnoreCase | RegexOptions.Compiled);
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: Do we want `IgnoreCase` here?  ISE only accepts `#region` not `#Region` or `#REGION` or `#rEgIoN`.  Given that the VSCode allows #region and #Region but not any other combination, this regex should drop the `IgnoreCase` and use `@"^\s*#[rR]egion\b"` to match the VSCode defintion.  Same goes for endregion below - `@"^\s*#[eE]nd[rR]egion\b" - which allows unfortunate combo's like `endRegion` and `Endregion`.  Oh well.

File: src/PowerShellEditorServices/Language/FoldingReference.cs [hunk 13]
```diff
@@ -60,4 +61,33 @@ public class FoldingReference: IComparable<FoldingReference>
...
+    /// </summary>
+    public class FoldingReferenceList : Dictionary<int, FoldingReference>
+    {
+        /// <summary>
+        /// Adds a FoldingReference to the list and enforces ordering rules e.g. Only one fold per start line
+        /// </summary>
+        public void SafeAdd(FoldingReference item)
+        {
+            if (item == null) { return; }
+            FoldingReference currentItem;
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Language/FoldingReference.cs]: Insert blank line here.

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs (hunk 4 above)
Comment (glennsarti) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: There are serialization errors when passing `IEnumberable<FoldingReference>` because the LSP needs `FoldingRange[]` (https://github.com/PowerShell/PowerShellEditorServices/blob/fbe88715a9b20ecc31a6827756f58225a336ded1/src/PowerShellEditorServices.Protocol/LanguageServer/Folding.cs#L40)

And by errors I mean the serialization does not conform to the LSP specification.  Which is why I do an object conversion.  I tried to keep the number of array creations/copies to a minimum

File: src/PowerShellEditorServices/Language/FoldingReference.cs (hunk 5 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/FoldingReference.cs]: Apologies.  My rubyisms coming through again.  Fixed to use more C#-isms

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs (hunk 4 above)
Comment (glennsarti) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: > Could you assign TokenOperations.FoldableRegions(script.ScriptTokens).ToArray() to an intermediate variable (foldableRegions?) for better debuggability and so this foreach doesn't have to wrap to a second line?

I can.  I was trying to avoid creating array copies.

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 7 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Fixed

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 8 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Fixed

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 9 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Fixed

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 11 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Fixed

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 12 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Nice pickup! Fixed.

File: src/PowerShellEditorServices/Language/FoldingReference.cs (hunk 13 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/FoldingReference.cs]: Fixed

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs (hunk 4 above)
Comment (rkeithhill) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: Using intermediates variables won't cause array copies.

> There are serialization errors when passing IEnumberable<FoldingReference>

Comment (glennsarti) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: Fixed.  Went with
`foreach (KeyValuePair<int, FoldingReference> entry in TokenOperations.FoldableRegions(script.ScriptTokens))`

File: src/PowerShellEditorServices/Language/FoldingReference.cs [hunk 14]
```diff
@@ -60,4 +61,39 @@ public class FoldingReference: IComparable<FoldingReference>
             return string.Compare(this.Kind, that.Kind);
         }
     }
+
+    /// <summary>
+    /// A class that holds a list of FoldingReferences and ensures that when adding a reference that the
+    /// folding rules are obeyed, e.g. Only one fold per start line
+    /// </summary>
+    public class FoldingReferenceList : Dictionary<int, FoldingReference>
```
Comment (rjmholt) [inline src/PowerShellEditorServices/Language/FoldingReference.cs]: If this doesn't require the all the dictionary methods, I would opt for composition over inheritance, so that no methods are exposed that would allow an invalid state in the list.

File: src/PowerShellEditorServices/Language/FoldingReference.cs [hunk 15]
```diff
@@ -60,4 +61,39 @@ public class FoldingReference: IComparable<FoldingReference>
...
+        public void SafeAdd(FoldingReference item)
+        {
+            if (item == null) { return; }
+
+            // Only add the item if it hasn't been seen before or it's the largest range
+            if (TryGetValue(item.StartLine, out FoldingReference currentItem))
+            {
+                if (currentItem.CompareTo(item) == 1) { this[item.StartLine] = item; }
+            }
+            else
```
Comment (rjmholt) [inline src/PowerShellEditorServices/Language/FoldingReference.cs]: Can use `return` rather than `else` here

File: src/PowerShellEditorServices/Language/TokenOperations.cs [hunk 16]
```diff
@@ -21,103 +21,143 @@ internal static class TokenOperations
...
-                return (item.StartLine == foldableRegions[index - 1].StartLine);
-            });
+                // Regex's are very expensive.  Use them sparingly!
+                // Processing for #region -> #endregion
+                if (s_startRegionTextRegex.IsMatch(token.Text))
+                {
+                    tokenCommentRegionStack.Push(token);
+                    continue;
+                }
+                else if (s_endRegionTextRegex.IsMatch(token.Text))
```
Comment (rjmholt) [inline src/PowerShellEditorServices/Language/TokenOperations.cs]: No need for `else` given `continue` above

File: src/PowerShellEditorServices/Language/FoldingReference.cs (hunk 15 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/FoldingReference.cs]: This function returns void so the return doesn't seem to be needed.

File: src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs (hunk 4 above)
Comment (glennsarti) [reply src/PowerShellEditorServices.Protocol/Server/LanguageServer.cs]: When moving from inheritance to composition this has now changed to;
`foreach (FoldingReference fold in TokenOperations.FoldableReferences(script.ScriptTokens).References)`

File: src/PowerShellEditorServices/Language/TokenOperations.cs (hunk 16 above)
Comment (glennsarti) [reply src/PowerShellEditorServices/Language/TokenOperations.cs]: Fixed

File: src/PowerShellEditorServices/Language/FoldingReference.cs (hunk 15 above)
Comment (TylerLeonhardt) [reply src/PowerShellEditorServices/Language/FoldingReference.cs]: I think he meant:

```csharp
if (references.TryGetValue(item.StartLine, out FoldingReference currentItem))
{
    if (currentItem.CompareTo(item) == 1) { references[item.StartLine] = item; }
    return;
}

references[item.StartLine] = item;
```

**Comment by glennsarti** [comment]
Rebased due to conflict

**Comment by TylerLeonhardt** [comment]
@glennsarti can you deal with the last conflict?

@rjmholt can you look at this when you can? I know you're on your way back to Seattle so no rush

**Comment by glennsarti** [comment]
Stop merging other stuff :-)

**Comment by glennsarti** [comment]
Rebased, waiting on CI

**Comment by glennsarti** [comment]
@TylerLeonhardt Yeah whoops, broke after the rebase.  Also fixed up some codacy violations.
