### PR TITLE
Fix off-by-one error in validation within `GetOffsetAtPosition`

### LINKED ISSUE #1663: Failed to load PowerShellEditorServices with lspconfig (nvim)
Followed the instructions on: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#powershell_es
I only set the bundle_path, installed powershell from: https://aur.archlinux.org/packages/powershell/ and downloaded and unzipped the latest PowerShellEditorServices (3.1.0) in my home directory.

I get the error:

```
[START][2022-01-13 10:58:50] LSP logging initiated
[ERROR][2022-01-13 10:58:59] ...lsp/handlers.lua:404    "OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/completion 5 - System.ArgumentOutOfRangeException: Value is not between 1 and 0 (Parameter 'lineNumber')\nActual value was 1.\n   at Microsoft.PowerShell.EditorServices.Utility.Validate.IsWithinRange(String parameterName, Int32 valueToCheck, Int32 lowerLimit, Int32 upperLimit) in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Utility\\Validate.cs:line 46\n   at Microsoft.PowerShell.EditorServices.Services.TextDocument.ScriptFile.GetOffsetAtPosition(Int32 lineNumber, Int32 columnNumber) in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Services\\TextDocument\\ScriptFile.cs:line 414\n   at Microsoft.PowerShell.EditorServices.Handlers.PsesCompletionHandler.GetCompletionsInFileAsync(ScriptFile scriptFile, Int32 lineNumber, Int32 columnNumber) in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Services\\TextDocument\\Handlers\\CompletionHandler.cs:line 161\n   at Microsoft.PowerShell.EditorServices.Handlers.PsesCompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Services\\TextDocument\\Handlers\\CompletionHandler.cs:line 72\n   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)\n   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)\n   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='textDocument/completion' RequestId='5'"
[ERROR][2022-01-13 11:00:14] .../vim/lsp/rpc.lua:420    "rpc"   "pwsh"  "stderr"        "Exception encountered starting EditorServices. Exception logged in D:\\a\\1\\s\\src\\PowerShellEditorServices.Hosting\\Commands\\StartEditorServicesCommand.cs on line 252 in EndProcessing:\nSystem.Threading.ThreadStateException: Thread has not been started.\n   at System.Threading.Thread.Join(Int32 millisecondsTimeout)\n   at System.Threading.Thread.Join()\n   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.TriggerShutdown() in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Services\\PowerShell\\Host\\PsesInternalHost.cs:line 247\n   at Microsoft.PowerShell.EditorServices.Server.PsesLanguageServer.WaitForShutdown() in D:\\a\\1\\s\\src\\PowerShellEditorServices\\Server\\PsesLanguageServer.cs:line 164\n   at Microsoft.PowerShell.EditorServices.Hosting.EditorServicesRunner.CreateEditorServicesAndRunUntilShutdown() in D:\\a\\1\\s\\src\\PowerShellEditorServices.Hosting\\Internal\\EditorServicesRunner.cs:line 188\n   at Microsoft.PowerShell.EditorServices.Commands.StartEditorServicesCommand.EndProcessing() in D:\\a\\1\\s\\src\\PowerShellEditorServices.Hosting\\Commands\\StartEditorServicesCommand.cs:line 247\n"
```
in lspinfo it show as active/attached:
lsp_powershell_es

full command is:
`pwsh -NoLogo -NoProfile -Command ~/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath ~/PowerShellEditorServices -LogPath ~/.cache/nvim/powershell_es.log -SessionDetailsPath ~/.cache/nvim/powershell_es.session.json -FeatureFlags @() -AdditionalModules @() -HostName nvim -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal`

any ideas what this is and how to solve it?

### PR DESCRIPTION
**Pull request by andschwa**
The incoming line number is 1-indexed (not 0-indexed), so while the
lower limit was correctly set to 1, the upper limit was set to
`FileLines.Count` which could be 0, but 0 lines implies an upper limit
of 1 with this indexing. See `ScriptFile.GetLine` for the only other use
of this 1-index range validation.

Fixes #1663.

### CODE REVIEW

File: src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs [hunk 1]
```diff
@@ -411,7 +411,7 @@ public void ApplyChange(FileChange fileChange)
         /// <returns>The zero-based offset for the given file position.</returns>
         public int GetOffsetAtPosition(int lineNumber, int columnNumber)
         {
-            Validate.IsWithinRange("lineNumber", lineNumber, 1, this.FileLines.Count);
+            Validate.IsWithinRange("lineNumber", lineNumber, 1, this.FileLines.Count + 1);
```
Comment (SeeminglyScience) [inline src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs:414]: Maybe this should just be a separate check for `FileLines.Count == 0`? I feel like the check is correct here, it just doesn't account for empty? Maybe it should be `Math.Max(this.FileLines.Count, 1)`?

Comment (andschwa) [reply src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs:414]: The use of `IsWithinRange` does not work well with 1-indexed lists that could be empty. I agree this looks weird, but it's what's done here too:

https://github.com/PowerShell/PowerShellEditorServices/blob/149f5ac1089fef8344f8a5849a211a1ba9a88431/src/PowerShellEditorServices/Services/TextDocument/ScriptFile.cs#L230-L237

**Comment by andschwa** [comment]
@SeeminglyScience I'm going to merge this for now so that the user reported issue can be tested. We can revert if needed.
