### PR TITLE
change Enumerate* to Get*

### LINKED ISSUE #612: Using Find References on Linux causes Editor Services to crash with "too many open files"
Seems we're hitting OS limits for file handles while walking the project's folder structure.

Relevant stack trace:

```
   System.AggregateException: One or more errors occurred. (Too many open files) ---> System.IO.IOException: Too many open files
       at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
       at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()
       at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)
       at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
       at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
       at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.Workspace.RecursivelyEnumerateFiles(String folderPath)
       at Microsoft.PowerShell.EditorServices.LanguageService.<FindReferencesOfSymbol>d__18.MoveNext()
```

Related issues:

- vscode-powershell: https://github.com/PowerShell/vscode-powershell/issues/908
- ide-powershell: https://github.com/daviwil/ide-powershell/issues/1

### PR DESCRIPTION
**Pull request by tylerl0706**
As @daviwil mentioned in #612, 
> If you change those EnumerateDirectories/Files calls to GetDirectories/Files, it might take care of the problem. There's really no benefit to using the Enumerate variety since we're not streaming the results back anyway, it just seemed to be the right thing to do at the time.

He was correct! Changing the Enumerates to Gets did the trick. Verified this on macOS by opening up a big workspace and finding all references/go to definition.

Resolves #612 
Resolves https://github.com/PowerShell/vscode-powershell/issues/908
Resolves https://github.com/daviwil/ide-powershell/issues/1

### CODE REVIEW

File: src/PowerShellEditorServices/Workspace/Workspace.cs [hunk 1]
```diff
@@ -274,7 +274,7 @@ private IEnumerable<string> RecursivelyEnumerateFiles(string folderPath)
                 {
                     foundFiles =
                         foundFiles.Concat(
-                            Directory.EnumerateFiles(
+                            Directory.GetFiles(
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Workspace/Workspace.cs]: While you're at it, can you add the check for PathTooLongException below using a catch exception filter:
```
catch (Exception ex) when {ex is UnauthorizedException || ex is PathTooLongException) { ... }
```
You might want to check DirectoryNotFoundException in case someone deletes a dir while we're searching.

File: src/PowerShellEditorServices/Workspace/Workspace.cs [hunk 2]
```diff
@@ -278,10 +278,22 @@ private IEnumerable<string> RecursivelyEnumerateFiles(string folderPath)
                                 folderPath,
                                 pattern));
                 }
-                catch (UnauthorizedAccessException e)
+                catch (DirectoryNotFoundException e)
```
Comment (rkeithhill) [inline src/PowerShellEditorServices/Workspace/Workspace.cs]: 👍
