### PR TITLE
Fix tests in `Debugging/DebugServiceTests.cs` and simplify faulty script path logic

### LINKED ISSUE #1442: Fix tests in `Debugging/DebugServiceTests.cs`
This entire file is commented out with a note:

https://github.com/PowerShell/PowerShellEditorServices/blob/29e44b6ebdc63de70bd06538db03f3298ba2cfc6/test/PowerShellEditorServices.Test/Debugging/DebugServiceTests.cs#L1

### PR DESCRIPTION
**Pull request by andschwa**
This resolves #1442, and sets me up to add a test around debugging code that uses an object from `System.Windows.Forms`.

This PR also:

- Fixes some NullReferenceExceptions exposed by the restored tests
- Removes some broken script path logic
- Replaces some older hard-coded empty array logic with the newer .NET Standard API
- Fixes a deadlock that occurs when debugging is aborted

### CODE REVIEW

File: src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs [hunk 1]
```diff
@@ -1040,28 +1040,6 @@ public async Task ExecuteScriptWithArgsAsync(string script, string arguments = n
...
-                        .ProviderPath;
-
-                    workingDir = workingDir.TrimEnd(Path.DirectorySeparatorChar);
-                    scriptAbsPath = workingDir + Path.DirectorySeparatorChar + script;
-                }
-                catch (System.Management.Automation.DriveNotFoundException e)
-                {
-                    this.logger.LogHandledException("Could not determine current filesystem location", e);
-                }
-
```
Comment (rjmholt) [inline src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs:1064]: What's the explanation here?

**Review by rjmholt — COMMENTED** [review]
The restored test code looks good, but there seem to be some product changes that aren't explained or mentioned in the title or description. I've read through the commit descriptions, but I think it's worth adding an explanation of the changes and how they relate to the testing in the PR description for posterity.

File: src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs (hunk 1 above)
Comment (andschwa) [reply src/PowerShellEditorServices/Services/PowerShellContext/PowerShellContextService.cs:1064]: https://github.com/PowerShell/PowerShellEditorServices/pull/1540/commits/ad28c88d738cd178bd61dba400a65ba2fb5a64af

**Comment by andschwa** [comment]
Dang, these passed locally.

**Comment by andschwa** [comment]
> The restored test code looks good, but there seem to be some product changes that aren't explained or mentioned in the title or description. I've read through the commit descriptions, but I think it's worth adding an explanation of the changes and how they relate to the testing in the PR description for posterity.

The only posterity that exists _is_ Git commits. PRs disappear. We might not be on GitHub in five years (we weren't hardly more than five years ago!)

**Comment by rjmholt** [comment]
> The only posterity that exists is Git commits. PRs disappear. We might not be on GitHub in five years (we weren't hardly more than five years ago!)

Ok, well seeing as how it's just a copy and paste and others on the team tend to look at the PRs, I'll do it for you

**Comment by rjmholt** [comment]
@andschwa looks like you're still pushing commits, let me know when you want a review

**Comment by andschwa** [comment]
Dah they DO literally all pass locally now. Ugh checking CI.

**Comment by andschwa** [comment]
Yay, I did it, they're all working now in CI too. @rjmholt Could you kindly review, with specific attention to https://github.com/PowerShell/PowerShellEditorServices/pull/1540/commits/648cd3eb8a94d97a073cc3907ac7d989f61fb64a?

**Comment by andschwa** [comment]
Also we just went from 1,543 in CI to 1,829 🥳

**Review by rjmholt — APPROVED** [review]
